---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: gitops-runtime
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./prod-cluster/gitops-runtime
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client
