# ---
# The source is defined in the gotk-gitops-pipeline
# apiVersion: source.toolkit.fluxcd.io/v1beta1
# kind: GitRepository
# metadata:
#   name: flux-system
#   namespace: flux-system
# spec:
#   interval: 1m0s
#   ref:
#     branch: main
#   secretRef:
#     name: flux-system
#   url: https://github.com/openshift-fluxv2-poc/demo
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: webapp
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./prod-cluster/webapp
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client
